# Reload tmux.conf
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Set default shell
set-option -g default-shell /bin/zsh

# Fix colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Change prefix key to Ctrl + Space
unbind C-space
set -g prefix C-space
bind C-space send-prefix

# Enable mouse
set -g mouse on

# Increase line history (Default: 2000)
set-option -g history-limit 5000

# Jump to marked pane (mark with Prefix + m)
bind \` switch-client -t'{marked}'

# Base-1 windows and panes
set -g base-index 1
setw -g pane-base-index 1
# Better numbering
set -g renumber-windows on

# Smarter split hotkeys
bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"

bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"

# Swapping windows
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# Keep current path
bind c new-window -c "#{pane_current_path}"

# Toggle previous window
bind Space last-window

# Toggle previous session
bind-key C-Space switch-client -l

# Vimlike bindings
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r C-h resize-pane -L 15
bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-l resize-pane -R 15

# Join panes
bind y choose-window 'join-pane -h -s "%%"'
bind Y choose-window 'join-pane -s "%%"'

#
# Nested sessions
#

# Window navigation
bind -n M-h prev
bind -n M-l next

#
# Plugins
#
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Continuum
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
