#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 6

BSPWM="$HOME/.config/bspwm"

$BSPWM/rules.sh
$BSPWM/theme.sh
$BSPWM/colors/kanagawa

# Launch
$BSPWM/scripts/set-wallpaper.sh

# Fix java windows
wmname LG3D

# Autostart applications
autostart &
