#! /bin/sh

BSPWM="$HOME/.config/bspwm"

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 2 3 4 5 6
#bspc monitor DP-0 -d 0

# Colors
$BSPWM/colors/twilight

# Launch
#$BSPWM/configuremonitors.sh
$BSPWM/scripts/resetpolybar.sh
$BSPWM/scripts/wallpaper.sh

$BSPWM/rules.sh
$BSPWM/theme.sh

# Fix java windows
wmname LG3D
